# Generated by Django 3.1.1 on 2020-09-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
